"""LCM package __init__.py file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
"""

from .trunk_state_t import trunk_state_t
from .biped_trunk_state_t import biped_trunk_state_t
